[package]
name = "qiniu-download"
version = "1.0.1"
description = "Qiniu Resource (Cloud) Download SDK for Rust."
authors = ["Bachue Zhou <zhourong@qiniu.com>", "longbai <baishunlong@qiniu.com>", "qiniusdk <sdk@qiniu.com>"]
documentation = "https://docs.rs/qiniu-download"
repository = "https://github.com/qiniu/rust-download-sdk"
readme = "README.md"
edition = "2018"
keywords = ["qiniu", "storage", "sdk", "cloud"]
license = "MIT"

[dependencies]
base64 = "0.10.1"
sha-1 = "0.8.1"
url = "2.1.0"
hmac = "0.7.1"
crypto-mac = "0.7.0"
isahc = { version = "1.3.1", features = ["json"] }
once_cell = "1.4.1"
positioned-io = "0.2.2"
rand = "0.8.3"
multipart = { version = "=0.17.3", package = "qiniu-multipart" }
text_io = "0.1.8"
dashmap = { version = "4.0.2", features = ["serde"] }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
directories = "3.0.1"
log = "0.4.14"
toml = "0.5.8"
tap = "1.0.1"
num_cpus = "1.13.0"

[dev-dependencies]
futures = "0.3.5"
warp = "0.2.5"
tokio = { version = "0.2.22", features = ["rt-core", "blocking", "macros"] }
structopt = "0.3.18"
anyhow = "1.0.32"
env_logger = "0.8.2"
